# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'UI封装demo' do
pod 'Masonry'
end

target 'UI封装demoTests' do

end

target 'UI封装demoUITests' do

end

