# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'tu——sdk' do
pod ‘GPUImage’
end

target 'tu——sdkTests' do

end

target 'tu——sdkUITests' do

end

