# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '直播结束view' do
pod 'Masonry'
end

target '直播结束viewTests' do

end

target '直播结束viewUITests' do

end

