# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '123' do
pod 'SDWebImage'
pod 'UIView+AutoLayout'
end

target '123Tests' do

end

target '123UITests' do

end

