# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MD360PlayerDemo_test' do
pod 'MD360Player4iOS','~> 0.2.0'
pod 'VIMVideoPlayer', '~> 6.0'
pod 'AFNetworking', '~> 3.0'
pod 'PLPlayerKit', '~> 2.1.3'
end

target 'MD360PlayerDemo_testTests' do

end

target 'MD360PlayerDemo_testUITests' do

end

